version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 14

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-gh-actions:
        update-types:
          - minor
          - patch
      major-gh-actions:
        update-types:
          - major
    cooldown:
      default-days: 14
    commit-message:
      prefix: "ci(deps)"
